### ISSUE TITLE
Stuck Boss

### ISSUE THREAD

**Issue by vladislavglad** [MaxMraz/yarntown#2]
***Father Gascoigne*** gets stuck on a candlestick and is unresponsive - ***lets you hit him*** as much as you want without any retaliation. He only gets unstuck when you knock him back with a strong attack at the right angle.

***Here is a gif preview of the problem:***
![stuck-gascoigne](https://user-images.githubusercontent.com/53010628/87883744-6d78b400-c9d7-11ea-801b-d4263fcaa799.gif)

**Comment by MaxMraz** [comment]
Believe I fixed this-
His tracking attack has him take a step toward the hero between each attack- if this step couldn't be completed, he would freeze up trying to finish this movement. Only a visceral attack would dislodge him from this state because it enacted another movement on him.

Put in a case to handle if the movement between attacks can't be completed, should be fixed and was in my testing.
